baseURL = "/"
languageCode = "en-us"
title = "Friends of North Shore Elementary"
theme = "charity"
cloudinary_url = "https://res.cloudinary.com/du4ny2w9j/image/upload/"
googleAnalytics = "UA-124599662-1"

