---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/modules
  label: Modules
  create: all
  match: "**/*"
- type: directory
  path: content/questions
  label: Questions
  create: all
  match: "**/*"
upload_dir: themes/charity/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: '0.43'
